name: Deploy to REG.ru
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          source: './*'
          target: '/www/bxtestdom1.ru/local/'
          overwrite: true  # Перезаписывать существующие файлы
          strip_components: 1  # Игнорировать корневую папку репозитория
