name: Deploy to REG.ru via SFTP
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: '37.140.192.240'
          username: 'u3019460'
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './*'  # Изменили с local-dir
          remote_path: '/www/bxtestdom1.ru/local/'  # Изменили с server-dir
          # exclude и dangerous-clean-slate удалены - этот Action их не поддерживает
